### ISSUE TITLE
Remaining days turning negative after sleep

### ISSUE THREAD

**Issue by MAJ007** [macmule/ADPassMon#43] opened 2016-01-18 09:25 UTC
More often than not when returning a Mac from Sleep the date remaining until pwd reset will be negative. If you refresh the ticket or wait until the tool does it own interval check it displays the correct count down. Any ideas how to remedy this?

**Comment by Tranel** [comment] 2016-01-18 15:16
More or less the same here. After a reboot it shows -14 days and whatever I do it stays there. But that is wrong, means there is something wrong.

**Comment by MAJ007** [comment] 2016-01-19 15:30
@Tranel I think we are having a different issues as ours is fine on reboot and refreshing tickets displays the correct count down.

**Comment by MAJ007** [comment] 2016-01-19 17:23
See below log. For some reason its when ever it reverts to using the alt method it will display the incorrect value:

Jan 19 08:51:50 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   Using alt method
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   New pwdSetDate (16749.67)
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   ≥ plist value (1.674967E+4) so we use it
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   daysUntilExp: -69.69933
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   expirationDate: Tuesday, 10 November 2015 16:04:48
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]: Triggering notification…
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 08:51:50 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 08:51:50 MACHINENAME kernel[0]: PM response took 4207 ms (1027, ADPassMon)
Jan 19 08:52:05 MACHINENAME spindump[1836]: Saved spin report for ADPassMon version 2.20.12 (127) to /Library/Logs/DiagnosticReports/ADPassMon_2016-01-19-085205_MACHINENAME.spin
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]:     daysUntilExp: 20.305347222222
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 08:52:08 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 09:18:09 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 09:18:09 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 09:18:09 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 09:18:11 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 09:18:11 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 09:18:11 MACHINENAME ADPassMon[1027]:     daysUntilExp: 20.287256944444
Jan 19 09:18:11 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 09:18:11 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 09:18:11 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   Using alt method
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   New pwdSetDate (16749.67)
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   ≥ plist value (1.674967E+4) so we use it
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   daysUntilExp: -69.76859
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   expirationDate: Tuesday, 10 November 2015 16:04:48
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]: Triggering notification…
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 10:31:34 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 11:40:03 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 11:40:03 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 11:40:03 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 11:40:04 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 11:40:04 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 11:40:04 MACHINENAME ADPassMon[1027]:     daysUntilExp: 20.188726851852
Jan 19 11:40:04 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 11:40:04 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 11:40:04 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]:     daysUntilExp: 20.095625
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 13:54:08 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]:     daysUntilExp: 20.094571759259
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 13:55:39 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]:     daysUntilExp: 20.073310185185
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 14:26:16 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   Using alt method
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   New pwdSetDate (16749.67)
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   ≥ plist value (1.674967E+4) so we use it
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   daysUntilExp: -69.98867
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   expirationDate: Tuesday, 10 November 2015 16:04:48
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]: Triggering notification…
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...
Jan 19 15:48:29 MACHINENAME ADPassMon[1027]:   Keychain unlocked...
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]: Domain reachable.
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]: Starting auto process…
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]:   Found expireDateUnix in plist: 1454947910
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]:   Got expireDateUnix: 1454947910
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]:   Using msDS method
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]:     daysUntilExp: 19.987731481482
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]: ADPassMon password method selected
Jan 19 16:29:30 MACHINENAME ADPassMon[1027]: Testing Keychain Lock state...

**Comment by pmbuko** [comment] 2016-01-19 17:48
The way ADPassMon chooses between the _msDS_ and _alt_ methods is by the output of this command:

`dscl localhost read /Search/Users/$USER msDS-UserPasswordExpiryTimeComputed 2&> /dev/null`

If it sees `msDS-UserPasswordExpiryTimeComputed` in the results then it will use the msDS method. If you have more than one domain server (like most sites) and not all of them return this value, then your issue is probably not caused by a bug in ADPassMon.

**Comment by Tranel** [comment] 2016-01-20 07:42
However the issue (for me) was introduced with the latest version of the tool. Until then I really liked it.

**Comment by MAJ007** [comment] 2016-01-20 09:07
@pmbuko I do take that on board that its probably not a bug. But why does this only happen when the machine is woken from being asleep after a couple minutes?

**Comment by macmule** [comment] 2016-01-23 21:55
@MAJ007 how long is the mac asleep for for this issue to appear? Is it hours? Maybe the kerberos ticket has expired

@Tranel Could you possibly post a new issue incase it does differ from this? On reboot with a kerberos ticket should be ok

**Comment by Tranel** [comment] 2016-01-25 08:55
Hi, a reboot does not solve the issue. As long as I am in the company's network I have negative values. The issue startet with version 14. Does it really make sense to post a new issue?

**Comment by macmule** [comment] 2016-01-25 09:22
Let me have a look. 

I'm worried things are going to get confused though. 

Does your log look the same?

Regards,

Ben.

**Comment by macmule** [comment] 2016-01-25 09:48
@MAJ007 can you try the following:

`/usr/bin/dscl localhost read /Search/Users/$USER SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'`

Do you get multiple results?

Can both @MAJ007 & @Tranel try: https://gist.github.com/macmule/b4dcaa658bc83254029f

Please post results, redacting names as needed. That's a POC for moving ADPassMon to python. I'd be curious to see if it works.

**Comment by MAJ007** [comment] 2016-01-25 10:20
@macmule I get the following:

dscl localhost read /Search/Users/$USER SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'
130918196184278585
130918196184278585

**Comment by macmule** [comment] 2016-01-25 10:34
@MAJ007 thanks.. can you try the gist?

**Comment by macmule** [comment] 2016-01-25 10:37
@MAJ007 FWIW, the above does give an last set date of: Thu, 12 Nov 2015 16:33:38 GMT

(oops.. updated)

**Comment by MAJ007** [comment] 2016-01-25 10:40
@macmule the output I've given you is in a working scenario. I will post again when I suspend the machine for x minutes...

**Comment by macmule** [comment] 2016-01-25 10:50
@MAJ007 sure.. I'd be interested in the output of the gist whenever & the below:

`/usr/bin/dscl localhost read /Search/Users/$USER msDS-UserPasswordExpiryTimeComputed`

I'm just trying to break it down.

**Comment by richmac25** [comment] 2016-01-29 11:56
@macmule Im working with @MAJ007 here are the requested outputs while i was seeing a negative number. Ive changed any corp info so please disregard names and IP's.

MACHINENAME:~ user$ dscl localhost read /Search/Users/user SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'
130916455107526807
130916455107526807

MACHINENAME:~ user$ /usr/bin/dscl localhost read /Search/Users/user msDS-UserPasswordExpiryTimeComputed
No such key: msDS-UserPasswordExpiryTimeComputed
dsAttrTypeNative:msDS-UserPasswordExpiryTimeComputed: 130994215107526807

MACHINENAME:~ user$ python /Users/user/Desktop/PassMon.py 
ldap_sasl_interactive_bind_s: Local error (-2)
    additional info: SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/1.2.1@DOMAIN.COM) unknown)
ldap_sasl_interactive_bind_s: Local error (-2)
    additional info: SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/1.2.2@DOMAIN.COM) unknown)
ldap_sasl_interactive_bind_s: Local error (-2)
    additional info: SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/1.2.1@DOMAIN.COM) unknown while looking up 'ldap/3.1.2.1@1.2.1' (cached result, timeout in 1199 sec))
ldap_sasl_interactive_bind_s: Local error (-2)
    additional info: SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/1.2.2@DOMAIN.COM) unknown while looking up 'ldap/3.1.2.2@1.2.2' (cached result, timeout in 1199 sec))

------ SUMMARY ------
LDAP servers found: 38
LDAP server queried: dc01.subdomain.domain.com
LDAP lookup attempts: 5
Search base: DC=subdomain,DC=domain,DC=com
AD Node: /Active Directory/SUBDOMAIN/DOMAIN.com
Username: user 
uAC: 512
Password Status: Password Expires
pwdSetDateRaw: 130916455107526807
Epoch Set Date: 1447171910
Set Date: Tuesday, 10 November 2015 16:11:50
Epoch Now: 1453810771
Password Age: 90
Days since set: 76
Password Expires in: 14 
Password Expires: Monday, 08 February 2016 16:11:50
User Groups: 12
MACHINENAME:~ user$

**Comment by richmac25** [comment] 2016-02-05 14:54
@macmule just wondering if this helped at all?

**Comment by macmule** [comment] 2016-02-20 21:24
@richmac25 Ish, as it's from sleep.. I wonder if ADPassMon is reverting to the plist.

Can you or @MAJ007 try the below when it next happens, & advise if this might be where the minus date is coming from.

```
#!/bin/bash

plistExpDate=$(defaults read org.pmbuko.adpassmon expireDateUnix)

pwdSetDate=$(date -r $plistExpDate)

echo "plistExpDate:        $plistExpDate"
echo "pwdSetDate:          $pwdSetDate"
```

**Comment by macmule** [comment] 2016-02-27 16:02
@richmac25 & @MAJ007 Please test the latest release: https://github.com/macmule/ADPassMon/releases/tag/2.20.18

I've changed it so ADPassMon updates the plist when it calculates expiry via ldapsearch too (previously it was just msDS). 

When "offline" ADPassMon reads the value from the plist.. So i think what was happening was that ADPassMon was not updating the plist, & when waking from sleep it was seeing the mac as being "offline" & show displaying the wrong expiration date.

**Comment by richmac25** [comment] 2016-02-29 10:27
@macmule Thanks, we will test and come back to you.

**Comment by supra2nr** [comment] 2016-04-01 17:47
@macmule Ive got a weird issue with one machine here... I can log in and it shows the correct number of days... When my boss logs in on the same machine, he gets -16883 days (expiration of 1970)... Our accounts were made the same way by the same administrator.  Any idea of what is causing this?

**Comment by stevemillermac** [comment] 2016-04-01 17:49
@supra2nr does this happen to him on multiple macs? If so, check his AD account. We've seen that when the account doesn't expire the password.

**Comment by supra2nr** [comment] 2016-04-01 18:12
i just grabbed my macbook pro and logged in as him - it must be something in his profile then, because it is showing -18k+ days on my mac too... Our corporate policy is 60 days password expiration, so I will have to look into it.  Thanks for the response!

**Comment by macmule** [comment] 2016-04-12 21:14
Can you post some of ADPassMon's logs? (System.log, look for ADPassMon).

We might be able to put together what's up.

**Comment by macmule** [comment] 2016-05-16 07:10
Can you try: https://github.com/macmule/ADPassMon/releases/tag/2.20.20 ?

**Comment by MAJ007** [comment] 2016-05-16 08:50
Will test and update with findings...

**Comment by MAJ007** [comment] 2016-05-24 14:29
I've been running version 2.20.20 and have not had any issues. So far so good :)

**Comment by MAJ007** [comment] 2016-05-24 14:30
I've been running version 2.20.20 and have not had any issues. So far so good :)

**Comment by karlmikaelskar** [comment] 2016-05-24 14:34
Here are some logs from a machine that had the correct date, woke from sleep and had the incorrect date. then connected and now has the correct date.

May 24 15:38:34 CI0011619 spindump[4800]: Saved spin report for ADPassMon version 2.20.20 (145) to /Library/Logs/DiagnosticReports/ADPassMon_2016-05-24-153834_CI0011619.spin
May 24 15:38:39 CI0011619 ADPassMon[629]: Domain test timed out.
May 24 15:38:39 CI0011619 ADPassMon[629]: Starting auto process…
May 24 15:38:39 CI0011619 ADPassMon[629]:   Offline. Updating menu…
May 24 15:38:39 CI0011619 ADPassMon[629]: ADPassMon password method selected
May 24 15:38:39 CI0011619 ADPassMon[629]: Testing Keychain Lock state...
May 24 15:38:39 CI0011619 ADPassMon[629]:   Keychain unlocked...
May 24 15:42:54 CI0011619 ADPassMon[629]: Domain test timed out.
May 24 15:47:54 CI0011619 ADPassMon[629]: Domain test timed out.
May 24 15:52:54 CI0011619 ADPassMon[629]: Domain test timed out.
May 24 15:56:18 CI0011619 spindump[4800]: Saved spin report for ADPassMon version 2.20.20 (145) to /Library/Logs/DiagnosticReports/ADPassMon_2016-05-24-155618_CI0011619.spin
May 24 15:56:21 CI0011619 ADPassMon[629]: Domain reachable.
May 24 15:56:21 CI0011619 ADPassMon[629]: Starting auto process…
May 24 15:56:21 CI0011619 ADPassMon[629]:   Found expireDateUnix in plist: 1465482394
May 24 15:56:21 CI0011619 ADPassMon[629]:   Got expireDateUnix: 1465482394
May 24 15:56:21 CI0011619 ADPassMon[629]:   Using msDS method
May 24 15:56:21 CI0011619 ADPassMon[629]:     daysUntilExp: 16,020983796296
May 24 15:56:21 CI0011619 ADPassMon[629]: ADPassMon password method selected
May 24 15:56:21 CI0011619 ADPassMon[629]: Testing Keychain Lock state...
May 24 15:56:21 CI0011619 ADPassMon[629]:   Keychain unlocked...

**Comment by karlmikaelskar** [comment] 2016-05-24 14:37
And more logs from when the machine wakes up from sleep disconnected from network:

defaults read ~/Library/Preferences/org.pmbuko.ADPassMon.plist 
{
    expireDateUnix = 1465482394;
    isBehaviour2Enabled = 1;
    "menu_title" = "-41800d";
    pwdSetDate = "16931.6";
    selectedBehaviour = 2;
    tooltip = "Your password expires\nThu Jun  9 16:26:34 CEST 2016";
}

May 24 16:34:54 CI0011619 ADPassMon[629]: Domain test timed out.
May 24 16:35:14 CI0011619 ADPassMon[629]: Domain test timed out.
May 24 16:35:14 CI0011619 ADPassMon[629]: Starting auto process…
May 24 16:35:14 CI0011619 ADPassMon[629]:   Offline. Updating menu…
May 24 16:35:14 CI0011619 ADPassMon[629]: ADPassMon password method selected
May 24 16:35:14 CI0011619 ADPassMon[629]: Testing Keychain Lock state...
May 24 16:35:14 CI0011619 ADPassMon[629]:   Keychain unlocked...

**Comment by karlmikaelskar** [comment] 2016-05-24 14:40
And tried again once connected:
May 24 16:38:33 CI0011619 spindump[4800]: Saved spin report for ADPassMon version 2.20.20 (145) to /Library/Logs/DiagnosticReports/ADPassMon_2016-05-24-163833_CI0011619.spin
May 24 16:38:36 CI0011619 ADPassMon[629]: Domain reachable.
May 24 16:38:36 CI0011619 ADPassMon[629]: Starting auto process…
May 24 16:38:36 CI0011619 ADPassMon[629]:   Found expireDateUnix in plist: 1465482394
May 24 16:38:36 CI0011619 ADPassMon[629]:   Got expireDateUnix: 1465482394
May 24 16:38:36 CI0011619 ADPassMon[629]:   Using msDS method
May 24 16:38:36 CI0011619 ADPassMon[629]:     daysUntilExp: 15,991643518518
May 24 16:38:36 CI0011619 ADPassMon[629]: ADPassMon password method selected
May 24 16:38:36 CI0011619 ADPassMon[629]: Testing Keychain Lock state...
May 24 16:38:36 CI0011619 ADPassMon[629]:   Keychain unlocked...

defaults read ~/Library/Preferences/org.pmbuko.ADPassMon.plist 
{
    expireDateUnix = 1465482394;
    isBehaviour2Enabled = 1;
    "menu_title" = 15d;
    pwdSetDate = "16931.6";
    selectedBehaviour = 2;
    tooltip = "Your password expires\nThu Jun  9 16:26:34 CEST 2016";
}

**Comment by macmule** [comment] 2016-05-25 08:27
@karlmikaelskar please try the below in script editor:

```
set unixDate to "1465482394"
set todayUnix to do shell script "/bin/date +%s"

set daysUntilExp to ((unixDate - todayUnix) / 86400)
set daysUntilExpNice to round daysUntilExp rounding toward zero

display dialog (daysUntilExpNice as string) & "d"
```

**Comment by macmule** [comment] 2016-05-25 08:55
As per conversations with @karlmikaelskar on Slack..

the tooltip is correct, just the menu bar dates that are wrong.

**Comment by richmac25** [comment] 2016-05-25 16:04
Update - 20.20 is so far so good. I still have to test over VPN which is where i consistently used to get negative values but when in the office and moving between AP's or returning from sleep etc it appears stable.

**Comment by macmule** [comment] 2016-05-26 13:39
from @karlmikaelskar on slack:

> So last thing I saw yesterday i think was that when i clicked “recheck for blabla” when offline the negative bonkers date came back. I’ll verify
> 
> Yes, issue still there when offline and manually running “Re-check Expiration"

**Comment by MAJ007** [comment] 2016-05-26 13:58
Disabled all network interfaces, rebooted machine, logged in with mobile AD account, clicked re-check and works as expected...

**Comment by karlmikaelskar** [comment] 2016-06-08 09:24
CI0011619:~ root# grep -i adpassmon /var/log/system.log

Jun  8 10:48:47 CI0011619 ADPassMon[36292]: Running on OS 10.10.x

Jun  8 10:48:48 CI0011619 ADPassMon[36292]: Running under a locally cached network account.

Jun  8 10:48:48 CI0011619 ADPassMon[36292]: ADPassMon password method selected

Jun  8 10:48:51 CI0011619 ADPassMon[36292]: Domain test timed out.

Jun  8 10:53:54 CI0011619 ADPassMon[36292]: Domain test timed out.

_I connect to network and recheck_

Jun  8 10:54:54 CI0011619 ADPassMon[36292]: Domain reachable.

Jun  8 10:54:54 CI0011619 ADPassMon[36292]: Starting auto process…

Jun  8 10:54:54 CI0011619 ADPassMon[36292]:   Found expireDateUnix in plist: -2,147483648×10^+9

Jun  8 10:54:54 CI0011619 ADPassMon[36292]:   Got expireDateUnix: 1479119803

Jun  8 10:54:54 CI0011619 ADPassMon[36292]:   Using msDS method

Jun  8 10:54:54 CI0011619 ADPassMon[36292]:     daysUntilExp: 159,070706018519

Jun  8 10:54:54 CI0011619 ADPassMon[36292]: ADPassMon password method selected

Jun  8 10:54:54 CI0011619 ADPassMon[36292]: Testing Keychain Lock state...

Jun  8 10:54:54 CI0011619 ADPassMon[36292]:   Keychain unlocked...

_I wake from sleep when offline_

Jun  8 11:00:25 CI0011619 ADPassMon[36292]: Domain test timed out.

Jun  8 11:00:25 CI0011619 ADPassMon[36292]: Starting auto process…

Jun  8 11:00:25 CI0011619 ADPassMon[36292]:   Offline. Updating menu…

Jun  8 11:00:25 CI0011619 ADPassMon[36292]: ADPassMon password method selected

Jun  8 11:00:25 CI0011619 ADPassMon[36292]: Testing Keychain Lock state...

Jun  8 11:00:25 CI0011619 ADPassMon[36292]:   Keychain unlocked...

_when I'm offline and recheck manually it turns to a negative date._

_before sleep:_
defaults read ~/Library/Preferences/org.pmbuko.ADPassMon.plist 

{

```
expireDateUnix = 1479119803;

isBehaviour2Enabled = 1;

"menu_title" = 159d;

pwdSetDate = "16939.44";

selectedBehaviour = 2;

tooltip = "Your password expires\\nMon Nov 14 11:36:43 CET 2016";
```

}

_after sleep:_
defaults read ~/Library/Preferences/org.pmbuko.ADPassMon.plist 

{

```
expireDateUnix = 1479119803;

isBehaviour2Enabled = 1;

"menu_title" = "-41815d";

pwdSetDate = "16939.44";

selectedBehaviour = 2;

tooltip = "Your password expires\\nMon Nov 14 11:36:43 CET 2016";
```

}

**Comment by macmule** [comment] 2016-11-07 23:41
Please test: https://github.com/macmule/ADPassMon/releases/tag/154

**Comment by macmule** [comment] 2016-11-12 13:14
Please test: https://github.com/macmule/ADPassMon/releases/tag/155

**Comment by macmule** [comment] 2016-11-20 00:20
Please test: https://github.com/macmule/ADPassMon/releases/tag/163

@MAJ007, @Tranel, @richmac25, @supra2nr

**Comment by macmule** [comment] 2017-04-01 23:15
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.

**Closed as completed by macmule** 2017-04-01 23:15 UTC
Labels: bug, duplicate
